import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, RotateCcw, Sparkles, Wand2 } from "lucide-react";
import { useLocation, useSearch } from "wouter";
import { PageFrame, PageHeading } from "@/components/app-shell";
import { ToolMark } from "@/components/tool-card";
import { tools } from "@/data/tools";

const questions = [
  { label: "What are you making?", options: ["A web product", "A visual project", "A content system", "A research workflow"] },
  { label: "How do you like to work?", options: ["I write code", "I prefer visual tools", "I am learning", "I want an agent to help"] },
  { label: "What matters most right now?", options: ["Move quickly", "Keep full control", "Make it beautiful", "Learn the fundamentals"] },
];

export default function Advisor() {
  const [, setLocation] = useLocation();
  const search = useSearch();
  const initial = new URLSearchParams(search).get("idea") || "";
  const [idea, setIdea] = useState(initial);
  const [step, setStep] = useState(initial ? 0 : -1);
  const [answers, setAnswers] = useState<string[]>([]);
  const [done, setDone] = useState(false);
  const picks = useMemo(() => {
    if (answers.includes("A visual project") || answers.includes("Make it beautiful")) return [tools.find(t => t.id === "figma")!, tools.find(t => t.id === "midjourney")!, tools.find(t => t.id === "runway")!];
    if (answers.includes("I write code") || answers.includes("Keep full control")) return [tools.find(t => t.id === "cursor")!, tools.find(t => t.id === "supabase")!, tools.find(t => t.id === "vercel")!];
    return [tools.find(t => t.id === "v0")!, tools.find(t => t.id === "claude")!, tools.find(t => t.id === "vercel")!];
  }, [answers]);
  const choose = (answer: string) => { const next = [...answers]; next[step] = answer; setAnswers(next); if (step < questions.length - 1) setStep(step + 1); else setDone(true); };
  if (done) return <PageFrame><PageHeading eyebrow="Your recommendation / ready" title="A focused stack for your next move." description={`Built around “${idea || "your idea"}”. Start with the first tool, then earn the right to add the rest.`} action={<button onClick={() => { setDone(false); setStep(0); setAnswers([]); }} className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground" data-testid="button-restart-advisor"><RotateCcw className="size-4" /> Start over</button>} /><div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><div className="space-y-3">{picks.map((tool, index) => <div key={tool.id} className="af-glass flex items-center gap-4 rounded-2xl p-5"><span className="font-mono text-xs text-muted-foreground">0{index + 1}</span><ToolMark tool={tool} size="lg" /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-medium">{tool.name}</h2><span className="rounded-full bg-secondary/[.1] px-2 py-1 font-mono text-[9px] uppercase tracking-wider text-secondary">{index === 0 ? "Start here" : "Then"}</span></div><p className="mt-1 text-sm text-muted-foreground">{tool.bestFor}</p></div><a href={tool.url} target="_blank" rel="noreferrer" className="rounded-lg border border-white/10 p-2 text-muted-foreground hover:text-secondary" data-testid={`link-advisor-tool-${tool.id}`}><ArrowRight className="size-4" /></a></div>)}</div><div className="rounded-2xl border border-primary/20 bg-primary/[.06] p-6"><Sparkles className="mb-8 size-6 text-primary" /><div className="font-mono text-[10px] uppercase tracking-[.18em] text-primary">Why this mix</div><h2 className="af-display mt-3 text-2xl font-semibold tracking-[-.04em]">Momentum without the maze.</h2><p className="mt-4 text-sm leading-relaxed text-muted-foreground">This combination keeps your first loop small: make a thing, show it to someone, learn what to change. You can always add complexity later.</p><button onClick={() => setLocation("/stack")} className="mt-7 flex w-full items-center justify-center gap-2 rounded-lg bg-primary px-4 py-3 text-sm font-semibold text-primary-foreground" data-testid="button-send-to-stack">Open in my stack <ArrowRight className="size-4" /></button></div></div></PageFrame>;
  if (step === -1) return <PageFrame><div className="mx-auto max-w-3xl pt-12 text-center lg:pt-24"><div className="af-reveal mx-auto mb-5 grid size-14 place-items-center rounded-2xl border border-primary/30 bg-primary/[.1] text-primary"><Wand2 /></div><div className="mb-4 font-mono text-[10px] uppercase tracking-[.2em] text-secondary">The 60-second route</div><h1 className="af-display af-reveal text-5xl font-semibold leading-[.92] tracking-[-.07em] sm:text-7xl">Give your idea<br /><span className="text-primary">a direction.</span></h1><p className="mx-auto mt-6 max-w-lg text-muted-foreground">Answer three honest questions. Get a practical starting stack with a reason for every recommendation.</p><div className="af-glass mt-10 rounded-2xl p-3 text-left"><textarea value={idea} onChange={event => setIdea(event.target.value)} placeholder="I want to build..." className="min-h-[110px] w-full resize-none bg-transparent p-3 text-base outline-none placeholder:text-muted-foreground/60" aria-label="Your build idea" data-testid="textarea-advisor-idea" /><div className="flex justify-end border-t border-white/[.08] pt-3"><button onClick={() => setStep(0)} className="flex items-center gap-2 rounded-lg bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground" data-testid="button-start-advisor">Let's find the fit <ArrowRight className="size-4" /></button></div></div></div></PageFrame>;
  const question = questions[step];
  return <PageFrame><div className="mx-auto max-w-2xl pt-6 lg:pt-16"><div className="mb-10 flex items-center justify-between"><button onClick={() => step === 0 ? setStep(-1) : setStep(step - 1)} className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground" data-testid="button-advisor-back"><ArrowLeft className="size-4" /> Back</button><span className="font-mono text-xs text-muted-foreground">0{step + 1} <span className="opacity-50">/ 03</span></span></div><div className="mb-12 h-1 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-primary transition-all" style={{ width: `${((step + 1) / 3) * 100}%` }} /></div><div className="af-reveal"><div className="mb-3 font-mono text-[10px] uppercase tracking-[.2em] text-secondary">Your build / {idea || "unnamed idea"}</div><h1 className="af-display text-4xl font-semibold tracking-[-.055em] sm:text-5xl">{question.label}</h1><div className="mt-8 space-y-3">{question.options.map((option, index) => <button key={option} onClick={() => choose(option)} className="group flex w-full items-center justify-between rounded-2xl border border-white/[.1] bg-white/[.025] p-5 text-left transition hover:-translate-y-0.5 hover:border-secondary/40 hover:bg-secondary/[.06]" data-testid={`button-answer-${index}`}><span className="flex items-center gap-4"><span className="grid size-8 place-items-center rounded-lg border border-white/10 font-mono text-xs text-muted-foreground transition group-hover:border-secondary/40 group-hover:text-secondary">{String.fromCharCode(65 + index)}</span><span className="text-[15px]">{option}</span></span><ArrowRight className="size-4 text-muted-foreground transition group-hover:translate-x-1 group-hover:text-secondary" /></button>)}</div></div></div></PageFrame>;
}