import { useState } from "react";
import { ArrowRight, BookOpen, Check, Clock3, Lightbulb, MoveUpRight } from "lucide-react";
import { Link } from "wouter";
import { PageFrame, PageHeading } from "@/components/app-shell";

const guides = [
  { number: "01", title: "The 30-minute stack", description: "How to choose fewer tools and still make meaningful progress before lunch.", time: "6 min read", tag: "Start here", color: "border-primary/30 bg-primary/[.06]" },
  { number: "02", title: "Prototype before you commit", description: "A practical loop for testing the shape of an idea before building the machinery.", time: "8 min read", tag: "Product thinking", color: "border-secondary/30 bg-secondary/[.05]" },
  { number: "03", title: "When an AI builder is enough", description: "The honest handoff from generated prototype to code you want to own.", time: "7 min read", tag: "Build", color: "border-accent/30 bg-accent/[.05]" },
  { number: "04", title: "A beginner's first deployment", description: "The smallest path from local idea to a URL you can send to someone.", time: "5 min read", tag: "Ship", color: "border-white/15 bg-white/[.03]" },
];

export default function Guides() {
  const [open, setOpen] = useState("");
  return <PageFrame><PageHeading eyebrow="Field notes / from the forge" title="Better decisions compound." description="Short, useful notes for people making something real with a rapidly changing toolset." action={<span className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.15em] text-muted-foreground"><BookOpen className="size-4" /> 04 notes</span>} /><div className="space-y-3">{guides.map((guide, index) => <article key={guide.number} className={`group flex flex-col gap-5 rounded-2xl border p-5 transition hover:-translate-y-0.5 hover:border-secondary/40 sm:flex-row sm:items-center ${guide.color}`} data-testid={`card-guide-${index}`}><span className="font-mono text-xs text-muted-foreground">{guide.number}</span><div className="min-w-0 flex-1"><div className="mb-2 flex flex-wrap items-center gap-3"><span className="font-mono text-[10px] uppercase tracking-[.16em] text-secondary">{guide.tag}</span><span className="flex items-center gap-1 text-xs text-muted-foreground"><Clock3 className="size-3" />{guide.time}</span></div><h2 className="af-display text-2xl font-semibold tracking-[-.04em]">{guide.title}</h2><p className="mt-2 max-w-xl text-sm leading-relaxed text-muted-foreground">{guide.description}</p>{open === guide.number && <p className="mt-4 max-w-xl border-t border-white/10 pt-4 text-sm leading-relaxed text-foreground/80">Start by writing the outcome in one sentence. Then choose the smallest tool that can make that sentence tangible today. Revisit the stack only after you have learned something from a real person.</p>}</div><button onClick={() => setOpen(open === guide.number ? "" : guide.number)} className="flex size-11 shrink-0 items-center justify-center rounded-xl border border-white/10 text-muted-foreground transition group-hover:border-secondary/30 group-hover:text-secondary" aria-label={`Read ${guide.title}`} data-testid={`button-read-guide-${index}`}>{open === guide.number ? <Check className="size-4" /> : <MoveUpRight className="size-4" />}</button></article>)}</div><section className="mt-14 grid gap-5 rounded-3xl border border-white/[.08] bg-white/[.025] p-6 sm:grid-cols-[auto_1fr_auto] sm:items-center sm:p-8"><div className="grid size-12 place-items-center rounded-2xl bg-primary/[.12] text-primary"><Lightbulb className="size-5" /></div><div><h2 className="af-display text-2xl font-semibold tracking-[-.04em]">Have an idea but no words for it yet?</h2><p className="mt-1 text-sm text-muted-foreground">The advisor is built for fuzzy beginnings.</p></div><Link href="/advisor" className="flex items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground" data-testid="link-guides-advisor">Find a direction <ArrowRight className="size-4" /></Link></section></PageFrame>;
}